language: python
python:
  - "2.7"
  - "3.6"
git:
  depth: false
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script:
  - pytest
branches:
  only:
    - master
notifications:
  email: false
after_sucess:
  - echo "Travis CI built!"
